### ISSUE TITLE
Override connection (host) per indices

### ISSUE THREAD

**Issue by simion** [laurentguilbert/django-trampoline#1]
I really like how you wrote this project. However i cannot use it because I have a separate index which is stored on a different elasticsearch server. So, it would be nice to be able to override connection host for each index. The config would look like:

```
TRAMPOLINE = {
  'HOST': 'localhost',
  'INDICES': {
    'index_name': {
      'HOST': 'localhost:9201',  # this would override default host
      'models': (
        'app_name.models.ModelName',
      ),
    }
  },
  'OPTIONS': {
    'fail_silently': True,
    'disabled': False,
  },
}
```

The implementation is not complex, you just have to change `connection` property from trampoline_config, and turn it into a method which receives the index_name.

Any plans on implementing such feature?
Kind regards

**Comment by laurentguilbert** [comment]
Hi, I'm glad you like the project. :smile: 

It seems like an interesting idea, I'll try to work something out as soon as I can.

**Comment by simion** [comment]
I've studied how elasticsearch_dsl works with multiple connections, and implemented support in trampoline. Check https://github.com/laurentguilbert/django-trampoline/pull/4

**Comment by simion** [comment]
This can be closed 😉
